// angular/todo-list/src/app/components/add-list/add-list.component.ts
import { Component, Output, EventEmitter } from '@angular/core';


@Component({
  selector: 'app-add-list',
  templateUrl: './add-list.component.html',
  styleUrls: ['./add-list.component.css']
})
export class AddListComponent {
  title="Add Todo List";
  user={
    name:'',
    email:''
  };

  @Output() onAddData= new EventEmitter<{name:string,email:string}>();

  addToList(user:string,email:string){
    this.user.name=user;
    this.user.email=email;
    this.onAddData.emit({name:user,email:email},);
  }
  
   
}

<div class="container text-center my-4">
    <div class="row">
        <div class="col-8 offset-md-2">
            <h1 class="display-3 my-4">{{title}}</h1>
            <input type="text" #user placeholder="Enter name" required/><br>
            <input type="text" #emails placeholder="Enter email" required/><br>
            
            <button class="btn btn-success my-3 m-4" (click)="addToList(user.value,emails.value)">Add</button>
            
        </div>
       
    </div>
</div>

// react/todo-list/src/components/Add-list.js
import React from "react";
import { Button, Form, FormGroup, Input, Label } from "reactstrap";

function Add(){
    
    return (
        <div className="container text-center">
      <h1 className="display-4 my-4">Todo List</h1>
      <div className="row">
        <div className="col-8 offset-2">
        <Form>
    <FormGroup floating>
      <Input
        name="name"
        placeholder="Username"
        type="text"
        />
      <Label for="exampleEmail">
        Username
      </Label>
    </FormGroup>

    <FormGroup floating>
      <Input
        name="email"
        placeholder="Email"
        type="email"
        />
      <Label for="examplePassword">
        Email
      </Label>
    </FormGroup>

    <Button color="success">
      Add
    </Button>
  </Form>
        </div>
      
    </div>
  </div>
  );
}
export default Add;
