// react/todo-list/src/components/View-list.js
import React from "react";
import { Button, Table } from "reactstrap";

function View() {
    return (
<div className="container text-center my-4"><h1 className="display-5 my-4">View Todo List</h1>
    <div className="row table">
        <div className="col-3">Id</div>
        <div className="col-3">Name</div>
        <div className="col-3">Email</div>
        <div className="col-3">Action</div> 
    </div>
        <div className="row table" >
            <div className="col-3"></div>
            <div className="col-3"></div>
            <div className="col-3"></div>
            {/* <div className="col-3"><button className="btn btn-outline-danger" >remove</button></div>  */}
        </div>

    </div>
    );
  }
  
  export default View;

// angular/todo-list/src/app/components/view-list/view-list.component.ts
import { Component, Input, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'app-view-list',
  templateUrl: './view-list.component.html',
  styleUrls: ['./view-list.component.css']
})
export class ViewListComponent {

  @Input() data:any[]=[];
 
  @Output() removeItemData = new EventEmitter<number>();
 
  removeItem(id:number){
    this.removeItemData.emit(id);
  }
 

}

<div class="container text-center my-4"><h1 class="display-3 my-4">View Todo List</h1>
    <div class="row table">
        <div class="col-3">Id</div>
        <div class="col-3">Name</div>
        <div class="col-3">Email</div>
        <div class="col-3">Action</div> 
    </div>
        <div class="row table" *ngFor="let item of data">
            <div class="col-3">{{item[0]}}</div>
            <div class="col-3">{{item[1]}}</div>
            <div class="col-3">{{item[2]}}</div>
            <div class="col-3"><button class="btn btn-outline-danger" (click)="removeItem(item[0])" >remove</button></div> 
        </div>

</div>
